apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
stringData:
  credentials: |-
    [default]
    aws_access_key_id = AKIA4RKA7UR3TOTMUBF3
    aws_secret_access_key = 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
  config: |-
    [default]
    region = ap-southeast-2
