apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: load-task
spec:
  params:
  - name: SERVER_HOST
    type: string
  - name: SERVER_PORT
    type: string
  - name: AUDIO_DURATION
    type: string
  - name: PATH
    type: string
  workspaces:
    - name: output
  steps:
    - name: install-and-run-k6
      image: ubuntu
      script: |
        #!/usr/bin/env bash

        apt update -y && apt upgrade -y
        apt install curl -y
        curl -sL https://github.com/grafana/k6/releases/download/v0.41.0/k6-v0.41.0-linux-amd64.deb > package.deb
        dpkg -i package.deb

        if [[ -z "$(params.SERVER_HOST)" ]]; then
            exit 1
        fi
        if [[ -z "$(params.SERVER_PORT)" ]]; then
            exit 1
        fi
        k6 run -e HOST=$(params.SERVER_HOST) -e AUDIO_DURATION=$(params.AUDIO_DURATION) -e PORT=$(params.SERVER_PORT) $(workspaces.output.path)/$(params.PATH)/devsecops/k6/script.js


