---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/var/nfs/minio"
    server: $MODEL_SERVER