apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: decoding-sdk-worker-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
