objstoreConfig: |-
  type: "S3"
  config:
    bucket: "$BUCKET_NAME"
    endpoint: "s3.$REGION.amazonaws.com"
    access_key: "$AWS_ACCESS_KEY"
    secret_key: "$AWS_SECRET_KEY"
    insecure: true
    
query:
  enabled: true
  dnsDiscovery:
    sidecarsService: prometheus-operated
    sidecarsNamespace: monitoring

queryFrontend:
  enabled: true

bucketweb:
  enabled: true
  refresh: "10m"

compactor:
  enabled: true
  persistence:
    size: "10Gi"
    existingClaim: ""

storegateway:
  enabled: true
  persistence:
    size: "10Gi"
    existingClaim: ""

ruler:
  enabled: false

receive:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
