# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: influxdb
#   name: influxdb
#   namespace: monitoring
# spec:
#   ports:
#   - port: 8086
#     protocol: TCP
#     targetPort: 8086
#   selector:
#     app: influxdb
#   type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: monitoring
spec:
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb-np
  namespace: monitoring
spec:
  ports:
  - port: 8086
    protocol: TCP
    nodePort: 30000
  selector:
    app: influxdb
  type: NodePort