readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  # If an ingress *path* other than the root (/) is defined, it should be reflected here
  # A trailing "/" must be included
  sonarWebContext: /sonarqube/
  # sonarWebContext: /sonarqube/

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 6
  # If an ingress *path* other than the root (/) is defined, it should be reflected here
  # A trailing "/" must be included
  sonarWebContext: /sonarqube/
  # sonarWebContext: /sonarqube/
  # If an ingress *path* is defined, it should be reflected here
  sonar.web.context: /sonarqube

startupProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 24
  # If an ingress *path* other than the root (/) is defined, it should be reflected here
  # A trailing "/" must be included
  sonarWebContext: /sonarqube/
  # sonarWebContext: /sonarqube/
env:
  # If you use a different ingress path from /, you have to add it here as the value of SONAR_WEB_CONTEXT
  - name: SONAR_WEB_CONTEXT
    value: /sonarqube